name = "githubproxy"
zone_id = ""
account_id = "d6252a570c309c113744c9e11317e271"
route = ""
workers_dev = true
compatibility_date = "2022-07-31"
type = "javascript"

[build]
command = "yarn build"

[build.upload]
format = "service-worker"
